yatube/about/urls.py
from django.urls import path
from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("create/", views.post_create, name="post_create"),
]

yatube/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
]

yatube/yatube/urls.py
"""yatube URL Configuration."""

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("about/", include("about.urls", namespace="about")),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls)
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

CHARS_OF_POST_TEXT = 15


class Group(models.Model):
    title = models.CharField("Название группы", max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        "Текст поста",
        help_text="Введите текст поста"
    )
    pub_date = models.DateTimeField(
        "Дата публикации",
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Автор"
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="posts",
        verbose_name="Группа",
        help_text="Выберите группу",
    )

    def __str__(self):
        return self.text[:CHARS_OF_POST_TEXT]

    class Meta:
        ordering = ["-pub_date"]

yatube/posts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group")
        labels = {
            "text": _("Текст поста"),
            "group": _("Группа"),
        }
        help_texts = {
            "text": _("Введите текст поста"),
            "group": _("Выберите группу"),
        }

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("first_name", "last_name", "username", "email")

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = "about/author.html"


class AboutTechView(TemplateView):
    template_name = "about/tech.html"

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect

from .models import Group, Post
from .forms import PostForm

User = get_user_model()

POSTS_PER_PAGE = 10


def index(request):
    template = "posts/index.html"
    posts = Post.objects.all()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
        "posts": posts,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = "posts/group_list.html"
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
        "group": group,
        "posts": posts,
    }
    return render(request, template, context)


def profile(request, username):
    template = "posts/profile.html"
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author__username=username)
    posts_count = posts.count()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
        "posts_count": posts_count,
        "posts": posts,
        "author": author,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = "posts/post_detail.html"
    post = get_object_or_404(Post, id=post_id)
    posts_count = Post.objects.filter(author=post.author).count()
    context = {
        "posts_count": posts_count,
        "post": post,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = "posts/create_post.html"
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:profile", username=request.user)

    return render(request, template, {"form": form})


@login_required
def post_edit(request, post_id):
    template = "posts/create_post.html"
    post = get_object_or_404(Post, id=post_id)
    if request.user == post.author:
        form = PostForm(request.POST, instance=post or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("posts:post_detail", post_id=post_id)

        form = PostForm(instance=post)
        return render(request, template,
                      {"post": post,
                       "form": form,
                       "is_edit": True})

    return redirect("posts:post_detail", post_id=post_id)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("posts:index")
    template_name = "users/signup.html"

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h2>Привет! Это послание от автора</h2>
<p>
  <p>
    Немного позже я попробую использовать здесь разные инструменты верстки
    <p>А пока — лови фотодиптих про самого печального белого кота Тбилиси:</p>
  </p>
    <img src="https://lh3.googleusercontent.com/ZfBLOQSvdhtIB-M9aVbZoh03KRxUKHE-gMX5PPQR3OtMwoTBZSVymcAclBFzoLgUwjBzqH45gDk90lcu_PwqfEfHF3PFGtl6MHhRtai8z_calwHWe-XsWJNZWuOKOTdLlDnjIIIHS4ygtJzkDYwbFE4tV5liWB22dLenHbykcMrb0cTPIpQDRaUFiLrvOUQAkmQaSe439CXOcxjJM-3evxHXfW-EMoBN_cqfbGWWrOnzYHPi_-LIuGxI75omtqN_qLogNzHR3u-pxR-kXe5lwmcGnbksV17ljZM2R7XX2alJ4g1WqhaIqIS_6iR7px2JNqGbv4De0uiI_KQ2s8wrUOcbu9PyJHe7TzYgl5yLKe6ygYoD2UjBeNKeeRwATdybgkZNhJpxC_dwmdPZeXhGAbOjOu4UCgDL3j9kqhhKxmlDyqRVb9bGHK7H8LEytmYTq2mjNOeyYmBXrn_PVvm92oUKwKHhb0YB2GSBA6qUySHpy64loKz47pck1a1FV2e-Nd_HdXZqdIU1hgV0WT5Md5xd-TJJwcRhjEF7OvqOTjyOYYhOcgOjIlyr9RSAl5GxqiN2h0pp_fPQB1yM7uXE3Q7WcpLsZukiQwuSnPlsbHGmvVRLfV6N5BeqVonYL5buR90hSd1iVRTR398aEyrGM-fCICoL4yJJctflLI_JuUh_N3Ucfzr_RvxkIpVAhPS6Nj9Ps4hRDTxg7V14W4PlLdWk=w708-h943-no?authuser=0" width="380" height="500"> 
    <img src="https://lh3.googleusercontent.com/pw/AM-JKLVKHGzyGwpaMJWtHr-evVilox4F9HPQogpf80wvV_AtTMvE9Ms_hGBc_VXeiWq1PhkEfVIK-yEU4uzxMpWv24s_701DMoFrLkF3toQiNFPPuqyc0hsz97ZC8pPdHBVMjdadk4tBEO-T8YAy5ZfXwezzHA=w708-h943-no?authuser=0" width="380" height="500"> 
  </p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row">
  <h2>Не исключено, что это как-то использовалось при создании сайта:</h2>
  <p></p>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
      <li class="list-group-item">
        SQL
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>{# Текст статьи #}</p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %} Последние обнволения {%endblock%}</title>
  </head>
  <body>
    <header>
      {% include "includes/header.html" %}
    </header>
    <main> 
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        {% block content %} {% endblock %}
      </div>
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
      {% include "includes/footer.html" %}    
    </footer>
  </body>

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url "posts:index" %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="YaLogo">
      <span style="color:red">Ya</span>tube</a>
    </a>

    {% with request.resolver_match.view_name as view_name %}

    <ul class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link {% if view_name  == "about:author" %}active{% endif %}" 
        href="{% url "about:author" %}">Об авторе</a>
      </li>

      <li class="nav-item">
        <a class="nav-link {% if view_name  == "about:tech" %}active{% endif %}" 
        href="{% url "about:tech" %}">Технологии</a>
      </li>

      {% if user.is_authenticated %}

      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == "posts:post_create" %}active{% endif %}" 
        href="{% url "posts:post_create" %}">Новая запись</a>
      </li>

      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == "password_change" %}active{% endif %}" 
        href="{% url "password_change" %}">Изменить пароль</a>
      </li>

      <li class="nav-item">
        <a class="nav-link link-light" href="{% url "logout" %}">Выйти</a>
      </li>

      <li>
        Пользователь: {{ user.username }}
      <li>

      {% else %}

      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == "login" %}active{% endif %}" 
        href="{% url "login" %}">Войти</a>
      </li>

      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == "users:signup" %}active{% endif %}" 
        href="{% url "users:signup" %}">Регистрация</a>
      </li>
      
      {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %} 
    Редактировать пост 
  {% else %} 
    Добавить пост 
  {% endif %}
{% endblock %}
  {% block content %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать пост 
            {% else %} 
              Добавить пост 
            {% endif %}    
          </div>
          <div class="card-body">
            {% if is_edit %}
              <form method="post" action="{% url "posts:post_edit" post.id %}">
            {% else %}
              <form method="post" action="{% url "posts:post_create" %}">
            {% endif %}
              {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    Текст поста                  
                    <span class="required text-danger" >*</span>                  
                  </label>
                    {{ form.text }}
                  <small id="id_text-help" class="form-text text-muted">
                    Создать или редактировать пост
                  </small>
                </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                  
                    </label>
                    {{ form.group }}
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %} {{ group }} {% endblock %}
{% block content %}
  <h1> {{ group }} </h1>
  <p> {{ group.description }} </p>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <br><a href="{% url "posts:profile" post.author.username %}"> Все записи автора </a></br>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
      <a href="{% url "posts:post_detail" post.id %}"> Подробная информация </a>
    </article>
      {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/includes/paginator.html
    {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation" class="my-5">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
              Предыдущая
            </a>
          </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item active">
                <span class="page-link">{{ i }}</span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
              Следующая
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
              Последняя
            </a>
          </li>
        {% endif %}    
      </ul>
    </nav>
    {% endif %} 

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <br><a href="{% url "posts:profile" post.author.username %}"> Все записи автора </a></br>  
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
      <p><a href="{% url "posts:post_detail" post.id %}">Подробная информация </a></p>
      {% if post.group %}
        <a href="{% url "posts:group_list" post.group.slug %}">Все записи группы {{ post.group }}</a>
      {% endif %}
    </article>
      {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %} Пост «{{ post.text|truncatechars:30 }}» {% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        {% if post.group %}   
          <li class="list-group-item">
            Группа: {{ post.group }}
            <p>
              {% if post.group %}
                <a href="{% url "posts:group_list" post.group.slug %}">Все записи группы {{ post.group }}</a>
              {% endif %}
            </p>  
        {% endif %}    
          </li>
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span >{{ posts_count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url "posts:profile" post.author.username %}">
            Все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p> {{ post.text }} </p>
      {% if request.user == post.author %}
      <a class="btn btn-primary" href="{% url "posts:post_edit" post.id %}">
        редактировать запись
      </a>
      {% endif %}
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %} Профайл пользователя {{ author.username }} {% endblock %}
{% block content %}
  <h1>Все посты пользователя {{ author.get_full_name }} ({{ author.username }}) </h1>
  <h3>Всего постов: {{ posts_count }} </h3>
  {% for post in page_obj %}
    <article>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      <p>{{ post.text }}</p>
      {% if post.group %}
        <a href="{% url "posts:group_list" post.group.slug %}">Все записи группы {{ post.group }}</a>
      {% endif %}
      <p><a href="{% url "posts:post_detail" post.id %}">Подробная информация </a></p>
    </article>       
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}  
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {% include "registration/includes/form_mistake.html" %}
          <form method="post" action="{% url "users:signup" %}">
            {% include "registration/includes/form_body.html" %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
          </form>
        </div> <!-- card body -->  
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %} 